/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_asu_sma_NodeContainer */

#ifndef _Included_edu_asu_sma_NodeContainer
#define _Included_edu_asu_sma_NodeContainer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_asu_sma_NodeContainer
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_asu_sma_NodeContainer_create
  (JNIEnv *, jobject);

/*
 * Class:     edu_asu_sma_NodeContainer
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_asu_sma_NodeContainer_dispose
  (JNIEnv *, jobject);

/*
 * Class:     edu_asu_sma_NodeContainer
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_asu_sma_NodeContainer_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
