import os
import os.path

PROJROOT = os.path.realpath('../../')
LIB = PROJROOT.join('lib/')
INC = PROJROOT.join('include/')

def configure(conf):
  conf.load('compiler_cxx')
  global LIB
  global INC
  conf.env.LIBPATH.append(LIB)
  conf.env.INCLUDES.append(INC)
  conf.check(
      compiler='cxx'
    , lib='smapp'
    , mandatory=True
    , uselib_store='SMAPP'
  )
  conf.check(
      compiler='cxx'
    , lib='smans'
    , mandatory=True
    , uselib_store='SMANS'
  )
def build(bld):
  obj = bld.create_ns3_program('example', ['csma', 'internet'])
  obj.cxxflags = ['-std=c++11']
  obj.source = [
    'example.cc'
  ]
  obj.use.append('SMAPP')
  obj.use.append('SMANS')
