#!/bin/bash

# Remove type parameters from typenames,
# then color type and function names
sed 's/\[with .*\]//g' | \
  perl -pe 's/(?<=\]\s)((?:[^:]*::(?=[^:]+::))*)([^:]+)::([\~a-zA-Z0-9]*\(.*)(?=\s\()/\033[33m\2\33[m::\033[32m\3\033[m/g' | \
perl -pe 's/(\s\([^:]*:[0-9]*\)\s)/\033[30m\1\33[m/g'
