if(depend_cmake_included)
  return()
endif()
set(depend_cmake_included ON)

function(depend project_name)
  if (NOT ${project_name})
    message(FATAL_ERROR "Dependency \${${project_name}} is not defined.")
  endif()
  return(${project_name})
endfunction()
