############################################
# OBJECTS

macro(object OBJ GROUP)
  foreach (_src ${ARGN})
    if (O_${_src})
      set(O_${OBJ} ${O_${OBJ}} ${O_${_src}})
    elseif (NOT ${_src} MATCHES "__EVERYTHING__")
      set(O_${OBJ} ${O_${OBJ}} ${_src})
    endif()
  endforeach()
  source_group("main\\${GROUP}" FILES ${O_${OBJ}})
  set(O___EVERYTHING__ ${O___EVERYTHING__} ${O_${OBJ}})
endmacro(object)


############################################
# TESTING            (cmake -Dbuild_tests=ON)

if (build_tests)
  message               (STATUS "Building test projects")
  add_subdirectory      (${LIB_GTEST})
  include_directories   (${gtest_SOURCE_DIR}/include)
  set_target_properties (gtest       PROPERTIES FOLDER ${TEST_PROJ_FOLDER})
  set_target_properties (gtest_main  PROPERTIES FOLDER ${TEST_PROJ_FOLDER})

  macro(add_test OBJ)
    if (O_${OBJ})
      set(T_${OBJ} ${O_${OBJ}})
    endif()
    foreach(_src ${ARGN})
      if (O_${_src})
        set(T_${OBJ} ${T_${OBJ}} ${O_${_src}})
      else()
        set(TT_${OBJ} ${TT_${OBJ}} ${_src})
      endif()
    endforeach()
    set(T_${OBJ} ${T_${OBJ}} ${TT_${OBJ}})
    if (NOT T_${OBJ})
      message(FATAL_ERROR "No sources supplied for test: ${OBJ}")
    else()
      if (TT_${OBJ})
        source_group("test\\${GROUP}" FILES ${TT_${OBJ}})
      endif()
      add_executable        (${OBJ}_test ${T_${OBJ}})
      target_link_libraries (${OBJ}_test gtest_main)
      set_target_properties (${OBJ}_test PROPERTIES FOLDER ${TEST_PROJ_FOLDER})
      message(STATUS "Added test: ${OBJ}")
    endif()
  endmacro(add_test)
else()
  macro(add_test)
  endmacro(add_test)
endif()

macro(add_exe OBJ)
  if (O_${OBJ})
    set(E_${OBJ} ${O_${OBJ}})
  endif()
  foreach(_src ${ARGN})
    if (O_${_src})
      set(E_${OBJ} ${E_${OBJ}} ${O_${_src}})
    else()
      set(E_${OBJ} ${E_${OBJ}} ${_src})
      source_group("main" FILES ${_src})
    endif()
  endforeach()
  if (NOT E_${OBJ})
    message(FATAL_ERROR "No sources supplied for executable: ${OBJ}")
  else()
    add_executable(${OBJ} ${E_${OBJ}})
    message(STATUS "Added executable: ${OBJ}")
  endif()
endmacro(add_exe)